### ISSUE TITLE
Dependency conflict with chromadb

### ISSUE THREAD

**Issue by imnotdev25** [joaomdmoura/crewAI-tools#57]
28.38 INFO: pip is looking at multiple versions of chromadb to determine which version is compatible with other requirements. This could take a while.
28.38 Collecting chromadb<0.5.0,>=0.4.22 (from crewai-tools>=0.2.7->-r requirements.txt (line 2))
28.41   Downloading chromadb-0.4.23-py3-none-any.whl.metadata (7.3 kB)
28.47   Downloading chromadb-0.4.22-py3-none-any.whl.metadata (7.3 kB)
28.83 ERROR: Cannot install crewai-tools because these package versions have conflicting dependencies.
28.83 
28.83 The conflict is caused by:
28.83     chromadb 0.4.24 depends on onnxruntime>=1.14.1
28.83     chromadb 0.4.23 depends on onnxruntime>=1.14.1
28.83     chromadb 0.4.22 depends on onnxruntime>=1.14.1
28.83

**Comment by nigel-daniels** [comment]
I'm seeing this error attempting to install into a docker container. Is there a work around or a back level recommended?

**Comment by nigel-daniels** [comment]
To recreate this error I have the following Docker file set up:
```
FROM alpine:latest

RUN apk update

RUN apk upgrade

RUN apk --no-progress --no-cache add autoconf automake make nasm gcc g++

RUN apk --no-progress --no-cache add libtool musl-dev zlib zlib-dev

RUN apk --no-progress --no-cache add git python3 py3-pip

RUN mkdir /usr/local/test

WORKDIR /usr/local/test

ENV VIRTUAL_ENV=/usr/local/test/.venv

RUN python3 -m venv $VIRTUAL_ENV

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt /usr/local/test

RUN pip install -r requirements.txt 

CMD ["/bin/sh"]
```
The `requirements.txt`  file I am using simply contains:
```
crewai[tools]
```
To recreate the error I ran:
```
docker build -t test .
```
This results in:
```
...
10.02   Downloading chromadb-0.4.23-py3-none-any.whl.metadata (7.3 kB)
10.04   Downloading chromadb-0.4.22-py3-none-any.whl.metadata (7.3 kB)
10.06 ERROR: Cannot install crewai-tools because these package versions have conflicting dependencies.
10.06 
10.06 The conflict is caused by:
10.06     chromadb 0.4.24 depends on onnxruntime>=1.14.1
10.06     chromadb 0.4.23 depends on onnxruntime>=1.14.1
10.06     chromadb 0.4.22 depends on onnxruntime>=1.14.1
10.06 
10.06 To fix this you could try to:
10.06 1. loosen the range of package versions you've specified
10.06 2. remove package versions to allow pip attempt to solve the dependency conflict
10.06 
10.06 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
...
```

**Comment by theS3b** [comment]
I can reproduce the same dependency conflict under a strict solver (`pixi` in my case), when trying to install `crewai[tools]>=0.126.0`.

Here is my minimal reproducible environment:

```toml
[project]
name = "CrewAIEnv"
version = "0.1.0"
authors = ["TheS3b"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.10,<=3.13"
ipykernel = "*"
pip = ">25.0"

[pypi-dependencies]
crewai = { version = "==0.130.0", extras = ["tools"] }
```

Running `pixi install` fails with:

```
embedchain>=0.1.114,<=0.1.127 depends on tiktoken>=0.7.0,<0.8.0
crewai-tools==0.47.1 depends on embedchain>=0.1.114 and tiktoken>=0.8.0
crewai[tools]==0.130.0 depends on crewai-tools>=0.47.1
...
chromadb depends on onnxruntime==1.22.0
embedchain==0.1.128 and onnxruntime==1.22.0 are incompatible
-> requirements unsatisfiable
```
Are there any options to make this resolvable under strict solvers like Pixi while staying on crewai[tools]>=0.130.0?
Thank you

**Comment by TomMeyer** [comment]
I was running into the same issue as @theS3b with pixi, with slightly different version. 

```
And because crewai-tools==0.49.0 depends on embedchain>=0.1.114 and tiktoken>=0.8.0, we can conclude that crewai-
      tools==0.49.0 depends on packaging>=23.2,<25.
      And because only crewai-tools<=0.49.0 is available and crewai[tools]==0.140.0 depends on crewai-tools>=0.49.0, we
      can conclude that crewai[tools]==0.140.0 depends on packaging>=23.2,<25.
      And because we know from (3) that crewai[tools]==0.140.0 depends on packaging==25.0, we can conclude that
      crewai[tools]==0.140.0 cannot be used.
```

Interestingly I found that if I put all the dependencies as pypi-dependencies it worked. 

```toml
[tool.pixi.environments]
default = ["default"]
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.pypi-dependencies]
mypackage = { path = ".", editable = true }
crewai = { version = ">=0.140.0", extras=["mcp", "tools"]}

[tool.pixi.feature.dev.pypi-dependencies]
ipykernel      = "==6.29.5"  
jupyterlab     = "==4.4.4"   
```

It seems to be related to the pin on packaging requiring  and how conda and pip dependencies are resolved by pixi. 

I found that I could use the conda dependencies if I pinned packaging to 24.2 in the conda dependencies. 

```toml
[tool.pixi.environments]
default = ["default"]
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.pypi-dependencies]
mtg_ai = { path = ".", editable = true }
crewai = { version = ">=0.140.0", extras=["mcp", "tools"]}



[tool.pixi.feature.dev.dependencies]
packaging    = "==24.2"
ipykernel      = "==6.29.5"  
jupyterlab     = "==4.4.4"               

```
